# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish nuget package

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .net 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack nuget
      run: dotnet pack --no-restore
    - name: Upload nuget package
      run: dotnet nuget push "bin/Release/Mohr.Jonas.Spaceshot.*.nupkg" --source "https://api.nuget.org/v3/index.json"
